## Inheritance 
- A class can inherit from other class
- It improves code reuse
- Constructor,attributes and methods are inherited to child class
- Parent class has no access to the child class
- child class methods overrides the parent class methods 
    - this is called method overriding
- `super()` method is used to invoke parent class methods and constructor

## Single inheritance 

In [9]:
class Person:
    def __init__(self,name):
        self.name = name
    def show(self):
        print(self.name + " is a python teacher")
class Professor(Person):
    def display(self):
        print(f"This is {self.name}")

In [6]:
per = Professor("Guido Rossum")

In [7]:
per.name

'Guido Rossum'

In [8]:
per.show()

Guido Rossum is a python teacher


In [10]:
per1 = Person("James")

In [11]:
per1.name

'James'

In [12]:
per1.show()

James is a python teacher


## Multilevel inheritance

In [13]:
class Human:
    def __init__(self,name):
        self.name = name
    def show(self):
        print(self.name)
class Person(Human):
    pass
class Professor(Person):
    pass
        

In [14]:
p = Professor("Guido Rossum")

In [15]:
p.name

'Guido Rossum'

In [16]:
p.show()

Guido Rossum


## Multiple Inheritance

In [17]:
class Person:
    def __init__(self,name):
        self.name = name
    def show(self):
        print(self.name)
class Teacher:
    def credit(self):
        print("He teaches python")
class PythonProgrammer(Person,Teacher):
    pass

In [18]:
p1 = PythonProgrammer("Guido Rossum")

In [19]:
p1.credit()

He teaches python


In [20]:
p1.name

'Guido Rossum'

In [21]:
p1.show()

Guido Rossum


## Hiearchical Inheritance 

In [22]:
class Human:
    def __init__(self,name):
        self.name = name
    def show(self):
        print(self.name + " is a Professor")
class PythonProgrammer(Human):
    pass
class JavaProgrammer(Human):
    pass

In [23]:
p = PythonProgrammer("Guido")

In [24]:
p.show()

Guido is a Professor


In [25]:
j = JavaProgrammer("James Gosling")

In [26]:
j.show()

James Gosling is a Professor


## Constructor Overriding

In [27]:
class Father:
    def __init__(self):
        self.money = 10000
        print("Father class constructor")
    def show(self):
        print("Father class method")
class Son(Father):
    def __init__(self):
        self.money = 500
        self.car = "BMW"
        print("Son class constructor")
    def display(self):
        print("Son class method")

In [28]:
s = Son()

Son class constructor


In [29]:
s.money

500

In [30]:
f = Father()

Father class constructor


In [31]:
f.money

10000

## `super() method`
- If we write constructor in both parent and child class, the parent class constructor is not available in child class
- `super()` method is used to call parent class from the child class

In [32]:
class Phone:
    def __init__(self,price,brand,camera):
        print("Inside phone class")
        self.price = price
        self.brand = brand
        self.camera = camera
    def buy(self):
        print("Buying a phone")
class Smartphone(Phone):
    def buy(self):
        print("Buying a smartphone")
        super().buy()
        

In [33]:
s = Smartphone(20000,"Iphone",13)

Inside phone class


In [34]:
s.buy()

Buying a smartphone
Buying a phone


### another example

In [35]:
class Father:
    def __init__(self):
        self.money = 10000
        print("Father class constructor")
    def show(self):
        print("Father class method")
class Son(Father):
    def __init__(self):
        super().__init__()
        print("Son class Constructor")
    def display(self):
        print("Son class method")
        

In [36]:
s = Son()

Father class constructor
Son class Constructor


In [37]:
s.money

10000

## Polymorphism
- Condition of occurence in different forms
- At operator level
- At function level
- At method level

## Example

In [38]:
class Car:
    def start(self):
        print("Engine started")
    def move(self):
        print("Car is running")
    def stop(self):
        print("Brakes applied")
class Clock:
    def move(self):
        print("Tick Tick Tick")

    def stop(self):
        print("Clock stopped")
class Person:
    def move(self):
        print("Person is moving")
    def stop(self):
        print("Person stopped")

### Method Overloading

In [39]:
c = Car()
cl = Clock()
p = Person()

In [40]:
def dosomething(x):
    x.move()
    x.stop()

In [41]:
dosomething(c)

Car is running
Brakes applied


In [42]:
dosomething(cl)

Tick Tick Tick
Clock stopped


In [43]:
dosomething(p)

Person is moving
Person stopped


## Operator overloading

In [44]:
2 + 3

5

In [45]:
"2" + "3"

'23'

## Function overloading

In [46]:
print(len('python'))
print(len(["ver1","ver2","ver3"]))
print(len({"Creator":"Guido", "Nationality":"Dutch"}))

6
3
2


## ABSTRACT CLASS
- A class derived from ABC class which belongs to abc module is known as `abstract class` in python
- ABC class is known as meta class which means class that defines behaviour of other classes.
- Abstract class can have concrete and abstract methods
- Abstract class needs to be extended and its methods implemented
- One cannot create objects of an abstract class

In [47]:
from abc import ABC, abstractmethod

class DefenceForce(ABC):

    def __init__(self):
        self.id = 101
    
    @abstractmethod
    def area(self):
        pass
    def gun(self):
        print("The Gun is AK 47")
        
    

In [52]:
class Army(DefenceForce):
    def area(self):
        print("Area is land", self.id)

In [53]:
a = Army()

In [54]:
a.area()

Area is land 101


In [56]:
a.gun()

The Gun is AK 47


In [57]:
a.id

101

In [58]:
class Navy(DefenceForce):
    def area(self):
        print("Area is Sea", self.id)

In [59]:
n = Navy()

In [61]:
n.area()

Area is Sea 101


In [63]:
n.gun()

The Gun is AK 47


## Create an abstract class Shape with abstract method `calculate_area`. Create two class Rectangle and circle inheriting from Shape. Create two objects of rectangle and circle and find the area of these objects

## 632
```
Implement the following hierarchy . The Book class has name, n (number of authors), authors (list of authors), publisher, ISBN, and year as its data members and the derived class has course as its data member. The derived class method overrides (extends) the methods of the base
class. 
```

In [ ]:
class Book:
    def __init__(self,name,n,authors,publisher,ISBN,year):
        self.name = name
        self.n = n
        self.authors = authors
        self.publisher = publisher
        self.ISBN = ISBN
        self.year = year
    def display(self):
        print(self.name)
        print(self.n)        
        print(self.authors)        
        print(self.publisher)        
        print(self.ISBN)        
        print(self.year)        
class DerivedBook(Book):
    def __init__(self,name,n,authors,publisher,ISBN,year,course):
        #super().__init__()
        self.course = course
    def display(self):
        #super().display()
        print(self.name)
        print(self.n)        
        print(self.authors)        
        print(self.publisher)        
        print(self.ISBN)        
        print(self.year) 
    
    

## METHOD RESOLUTION ORDER IN PYTHON
- It defines an order in which the class is searched in case of multiple inheritance.
- It is based on C3 Linearization Algorithm (>= Python 2.3)


## C3 Linearization Algorithm
**Notation**
- For a list of classes - C1C2C3..Cn
  - the C1 is the head of class and the rest is tail
- C3 Linearization Algorithm is defined as MRO of sum of any class C and the linear of parents and the list of parents
```
L(C(B1,B2...BN)) = C + merge(L(B1), L(B2) ...BN))
```
- Here B1 to BN are the parent classes of C
1. Take the head of first list L(B1) from left to right
2. If the head of selected class is not in the tail of the list, add it to the linear and remove it from the list
3. Repeat the process until the classes are removed or it is impossible to find good head


In [1]:
!python --version

Python 3.8.5


## EXAMPLE DEMONSTRATION

In [3]:
class F:
    pass
class E:
    pass
class D:
    pass
class C(D,F):
    pass
class B(D,E):
    pass
class A(B,C):
    pass

In [4]:
A.mro()

[__main__.A,
 __main__.B,
 __main__.C,
 __main__.D,
 __main__.E,
 __main__.F,
 object]

## First step
- MRO OF D,E,F,O
- L(D) = DO
- L(E) = EO
- L(F) = FO
- L(O) = O


## Second step
```
L(C) = C + MERGE(L(D),L(F),DF)
= C + MERGE(DO,FO,DF)
= C + D + MERGE(O,FO,F)
= C + D + F + O
= CDFO
```

##  Third Step
```
L(B) = B + MERGE(L(D),L(E),DE)
= B + MERGE(DO,EO,DE)
= B + D + MERGE(O,EO,E)
= B + D + E + O
= BDEO
```

## Fourth step 
```
L(A) = A + MERGE(L(B),L(C),BC)
= A + MERGE(BDEO, CDFO,BC)
= A + B + MERGE(DEO,CDFO,C)
= A + B + C + MERGE(DEO,DFO)
= A + B + C + D + MERGE(EO,FO)
= A + B + C + D + E + F + O
= ABCDEFO
```

## PB 604

In [5]:
class A:                 # AO
    pass
class B:                 # BO
    pass   
class C:                 # CO
    pass
class X(A,B):            # XABO
    pass
class Y(C,A,B):          # YCABO
    pass
class Z(A):              # ZAO
    pass
class P(Z,Y,X):          # P + MERGE(ZAO,YCABO,XABO,ZYX)
    pass

In [6]:
P.mro()

[__main__.P,
 __main__.Z,
 __main__.Y,
 __main__.C,
 __main__.X,
 __main__.A,
 __main__.B,
 object]

### Inconsistent MRO Design

In [7]:
class A:
    pass
class B:
    pass
class C(A,B):
    pass
class D(B,A):
    pass
class X(C,D):
    pass

TypeError: Cannot create a consistent method resolution
order (MRO) for bases A, B

## OPERATOR OVERLOADING
```
__add__ = +
__sub__ = -
__mul__ = *
__truediv__ = /
```

In [8]:
class Fraction:
    
    def __init__(self,x,y):
        self.num = x
        self.den = y
    
    def __add__(self,other):
        new_num = self.num*other.den + other.num*self.den
        new_den = self.den * other.den
        return f"{new_num}/{new_den}"
    
    def __sub__(self,other):
        new_num = self.num*other.den - other.num*self.den
        new_den = self.den * other.den
        return f"{new_num}/{new_den}"
    
    def __mul__(self,other):
        new_num = self.num * other.num
        new_den = self.den * other.den
        return f"{new_num}/{new_den}"
    
    def __truediv__(self,other):
        new_num = self.num * other.den
        new_den = self.den * other.num
        return f"{new_num}/{new_den}"
    
    def __str__(self):
        return f"{self.num} / {self.den}"
    
    def convert_decimal(self):
        return self.num / self.den
    
        

In [ ]:
Fraction1 = 1/3
Fraction2 = 2/5

In [9]:
f1 = Fraction(1,3)
f2 = Fraction(2,5)

In [10]:
f1 + f2

'11/15'

In [11]:
f1*f2

'2/15'

In [12]:
f1 / f2

'5/6'

In [13]:
print(f1)
print(f1.convert_decimal())

1 / 3
0.3333333333333333


## Comparison Operators
```
__eq__ -> ==
__lt__ -> <
__gt__ -> >

```

## WAP to create a class Data with data member value. Create two objects of the class to demonstrate comparison operators 

## PB 634
```
Create a class called Student, having name and email as its data members and _init_(self, name, email) and putdata(self) 
as bound methods. The _init_ function should assign the values passed as parameters to the requisite variables. The 
putdata function should display the data of the student. Create another class called PhDguide having name, email, and 
students as its data members. Here, the students variable is the list of students under the guide. The PhDguide class 
should have four bound methods: _init_, putdata, add, and remove. The _init_ method should initialize the variables, the 
putdata should show the data of the guide, include the list of students, the add method should add a student to the list of 
students of the guide and the remove function should remove the student (if the student exists in the list of students of 
that guide) from the list of students.
```

In [ ]:
class Student:
    def __init__(self,name,email):
        self.name = name
        self.email = email
    def putdata(self):
        print(self.name)
        print(self.email)
class PhDGuide:
    def __init__(self,name,email):
        self.name = name
        self.email = email
        self.students = []
        
    def put_data(self):
        print("Guide name", self.name)
        print("Guide email", self.email)
        print("Students under guide")
        
        for student in self.students:
            student.putdata()
            print("-------")
    def add(self,student):
        if student not in self.students:
            self.students.append(student)
            print("Student added")
    def remove(self,student):
        if student in self.students:
            self.students.remove(student)
            print("Student removed")
        else:
            print("Student not found")
            
        
        

# Numpy

In [1]:
import numpy as np

In [5]:
arr = np.array([1,2,3,4,5])

In [7]:
print(arr)
print(type(arr))
print(np.__version__)

[1 2 3 4 5]
<class 'numpy.ndarray'>
1.19.2


## 2D array

In [8]:
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


## 3D array 

In [12]:
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]],dtype = float)

In [13]:
print(c)

[[[1. 2.]
  [3. 4.]]

 [[5. 6.]
  [7. 8.]]]


## dtype

In [14]:
c.dtype

dtype('float64')

In [15]:
arr = np.array([1,2,3,0,0], dtype = bool)

In [16]:
print(arr)

[ True  True  True False False]


## Array attributes

### ndim  - return number of dimensions

In [29]:
a = np.array([0,1,2,3,4,5,6,7,8,9])
b = np.array([[1,2,3],[4,5,6]])
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]],dtype = float)

In [21]:
a2 = np.arange(10)

In [30]:
print(a)
print(b)
print(c)

[0 1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]]
[[[1. 2.]
  [3. 4.]]

 [[5. 6.]
  [7. 8.]]]


In [31]:
print(a.ndim)
print(b.ndim)
print(c.ndim)

1
2
3


## shape - to check the shape

In [32]:
print(a.shape)
print(b.shape)
print(c.shape)

(10,)
(2, 3)
(2, 2, 2)


## size of the array

In [33]:
print(a.size)
print(b.size)
print(c.size)

10
6
8


## itemsize - size in bytes of an array item

In [34]:
print(a.itemsize)
print(b.itemsize)
print(c.itemsize)

4
4
8


## dtype

In [35]:
print(a.dtype)
print(b.dtype)
print(c.dtype)

int32
int32
float64


## Reshape

In [39]:
a1 = np.arange(12).reshape(2,6)

In [40]:
print(a1)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


## Scalar operation 

In [43]:
print(a1 + 2) 
print(a1) # VIEW ONLY

[[ 2  3  4  5  6  7]
 [ 8  9 10 11 12 13]]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


In [44]:
print(a1*2)
print(a1/2)
print(a1//2)
print(a1**2)

[[ 0  2  4  6  8 10]
 [12 14 16 18 20 22]]
[[0.  0.5 1.  1.5 2.  2.5]
 [3.  3.5 4.  4.5 5.  5.5]]
[[0 0 1 1 2 2]
 [3 3 4 4 5 5]]
[[  0   1   4   9  16  25]
 [ 36  49  64  81 100 121]]


## np.sort - view only
- Returns a sorted copy of an array

In [45]:
a = np.array([58,67,12,45,53,89,93])

In [48]:
np.sort(a)[::-1]

array([93, 89, 67, 58, 53, 45, 12])

In [47]:
a

array([58, 67, 12, 45, 53, 89, 93])

## np.concatenate
- It concatenates a sequence of arrays along the existing axis

In [56]:
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)
print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [58]:
np.concatenate((c,d),axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

In [59]:
np.concatenate((c,d),axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

## Copy in list vs numpy

In [49]:
a = [1,2,3]
b = a
b[1] = 100
print(a)

[1, 100, 3]


## np.nditer

In [50]:
a = np.array([58,67,12,45,53,89,93])

In [51]:
for i in np.nditer(a):
    print(i)

58
67
12
45
53
89
93


In [52]:
a = np.array([0,1,2,3,4,5,6,7,8,9])
b = np.array([[1,2,3],[4,5,6]])
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]],dtype = float)

In [53]:
for i in b:
    print(i)

[1 2 3]
[4 5 6]


In [55]:
for i in np.nditer(b):
    print(i, end = " ")

1 2 3 4 5 6 

## np.where
- It returns the indices of elements in an input array where the given condition is satisfied

In [60]:
a = np.array([56,68,23,11,78,86,34,51,50])

In [61]:
np.where(a>50)

(array([0, 1, 4, 5, 7], dtype=int64),)

In [62]:
np.where(a>50,0 ,a)

array([ 0,  0, 23, 11,  0,  0, 34,  0, 50])

In [63]:
a

array([56, 68, 23, 11, 78, 86, 34, 51, 50])

In [64]:
np.where(a%2==0,0 ,a)

array([ 0,  0, 23, 11,  0,  0,  0, 51,  0])

## Splitting Arrays
- It is reverse of joining
- It breaks array into multiple arrays
- `array_split` is used with number of split as parameters to split the array

In [65]:
import numpy as np

In [70]:
arr = np.array([1,2,3,4,5,6,7])

In [72]:
np.array_split(arr,2)

[array([1, 2, 3, 4]), array([5, 6, 7])]

In [73]:
np.array_split??

## random in numpy

### randint

In [78]:
from numpy import random
x = random.randint(100)
print(x)

72


### rand

In [81]:
from numpy import random
x = random.rand(100)
print(x)

[0.44490552 0.64618986 0.57557964 0.81693814 0.39966064 0.59020909
 0.50163663 0.99203517 0.39463515 0.05384282 0.96382311 0.71170475
 0.48497938 0.95877866 0.77707155 0.13424292 0.40243714 0.60397887
 0.60482901 0.6739818  0.31135235 0.73939564 0.55729475 0.44002373
 0.70240003 0.43854956 0.5497212  0.08876453 0.71540537 0.91635155
 0.9079892  0.58984107 0.76259223 0.05716972 0.31294993 0.08924517
 0.13622525 0.2358049  0.34772046 0.53683034 0.73105105 0.26828679
 0.56217566 0.77444847 0.60790882 0.35645604 0.5449872  0.0346265
 0.6020992  0.99641143 0.49700611 0.87340058 0.78073184 0.82914681
 0.8808458  0.28804273 0.83837798 0.3560302  0.7987659  0.83413464
 0.27678907 0.32641032 0.81388265 0.15070895 0.13498193 0.75332995
 0.92791003 0.88316601 0.62565036 0.50797811 0.40259678 0.98654346
 0.99017491 0.301188   0.24001948 0.92158028 0.22388519 0.99779452
 0.0638552  0.79739631 0.70845863 0.79405097 0.16990709 0.26053732
 0.29105486 0.53696279 0.40010931 0.42471525 0.54982623 0.49801

In [80]:
from numpy import random
x = random.rand()
print(x)

0.049413251470032615


## 1 d array

In [84]:
from numpy import random
x = random.randint(100, size=(5))
print(x)

[43 89 28 94 80]


## 2d array 

In [85]:
from numpy import random
x = random.randint(100, size=(3,5))
print(x)

[[ 3 66 95 16 15]
 [62 43 82 83  2]
 [54 96 69 89 54]]


In [88]:
from numpy import random
x = random.rand(5)
print(x)

[0.63565914 0.93538102 0.65906207 0.48681843 0.95139038]


In [89]:
from numpy import random
x = random.rand(3,5)
print(x)

[[0.72581867 0.21695288 0.30481771 0.36026306 0.53440294]
 [0.21957001 0.93445532 0.14591345 0.00755266 0.39877984]
 [0.28525916 0.8964515  0.176928   0.6170826  0.48167336]]


## choice method
- It allows you to generate a random value based on the array 

In [96]:
x = random.choice([3,5,6,7,8])

In [97]:
print(x)

3


In [99]:
from numpy import random
x = random.choice([3,5,7,9], size=(3,5))
print(x)

[[5 5 3 9 7]
 [7 3 5 5 7]
 [9 5 5 9 9]]
